name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCHESHIRE_FETCH_SDL=ON
      - name: Compile
        run: cmake --build build --config Release --parallel 4
      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure
